Fix build failure after matrix-appservice-bridge types
Since commit 35421c4960c0 ("fix #5 - Types for
matrix-appservice-bridge"), the build fails with the following error:

  src/main.ts:55:68 - error TS2345: Argument of type 'null' is not assignable to parameter of type 'string | undefined'.

  55       murmur.setMatrixClient(bridge.getClientFactory().getClientAs(null));
                                                                        ~~~~

Pass no parameter to getClientAs() since apparently null isn't
permissible any longer.

Fixes: 35421c4960c0 ("fix #5 - Types for matrix-appservice-bridge")